services:
  backend:
    build:
      context: ./allomedia-backend
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/allomedia
      - PORT=5000
      - JWT_SECRET=$(openssl rand -base64 32)
      - EMAIL_USERNAME=otmankharbouch813@gmail.com
      - EMAIL_PASSWORD=ojmjivngevihrqve
      - MONGO_URI_TEST=mongodb://localhost:27017/allomedia_test
      - NODE_ENV=development
      - SESSION_SECRET=$(openssl rand -base64 32)
    volumes:
      - ./allomedia-backend:/app
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo_container_db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
      

  frontend:
    build:
      context: ./allomedia-front
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mongo_data:
    driver: local

networks:
  app-network:
    driver: bridge